package com.yrlapps.randomasiannamegenerator;

///////ALL OF THIS IS REFERENCED FROM THE JAKAROMA PROJECT BY NICOLAS RAOUL
import java.util.HashMap;
import java.util.Map;
public class KanaToRomaji {
    Map<String, String> m = new HashMap<String, String>();

    // Constructor
    public KanaToRomaji() {
        m.put("あ", "a");
        m.put("い", "i");
        m.put("う", "u");
        m.put("え", "e");
        m.put("お", "o");
        m.put("か", "ka");
        m.put("き", "ki");
        m.put("く", "ku");
        m.put("け", "ke");
        m.put("こ", "ko");
        m.put("さ", "sa");
        m.put("し", "shi");
        m.put("す", "su");
        m.put("せ", "se");
        m.put("そ", "so");
        m.put("た", "ta");
        m.put("ち", "chi");
        m.put("つ", "tsu");
        m.put("て", "te");
        m.put("と", "to");
        m.put("な", "na");
        m.put("に", "ni");
        m.put("ぬ", "nu");
        m.put("ね", "ne");
        m.put("の", "no");
        m.put("は", "ha");
        m.put("ひ", "hi");
        m.put("ふ", "fu");
        m.put("へ", "he");
        m.put("ほ", "ho");
        m.put("ま", "ma");
        m.put("み", "mi");
        m.put("む", "mu");
        m.put("め", "me");
        m.put("も", "mo");
        m.put("や", "ya");
        m.put("ゆ", "yu");
        m.put("よ", "yo");
        m.put("ら", "ra");
        m.put("り", "ri");
        m.put("る", "ru");
        m.put("れ", "re");
        m.put("ろ", "ro");
        m.put("わ", "wa");
        m.put("を", "wo");
        m.put("ん", "n");
        m.put("が", "ga");
        m.put("ぎ", "gi");
        m.put("ぐ", "gu");
        m.put("げ", "ge");
        m.put("ご", "go");
        m.put("ざ", "za");
        m.put("じ", "ji");
        m.put("ず", "zu");
        m.put("ぜ", "ze");
        m.put("ぞ", "zo");
        m.put("だ", "da");
        m.put("ぢ", "ji");
        m.put("づ", "zu");
        m.put("で", "de");
        m.put("ど", "do");
        m.put("ば", "ba");
        m.put("び", "bi");
        m.put("ぶ", "bu");
        m.put("べ", "be");
        m.put("ぼ", "bo");
        m.put("ぱ", "pa");
        m.put("ぴ", "pi");
        m.put("ぷ", "pu");
        m.put("ぺ", "pe");
        m.put("ぽ", "po");
        m.put("きゃ", "kya");
        m.put("きゅ", "kyu");
        m.put("きょ", "kyo");
        m.put("しゃ", "sha");
        m.put("しゅ", "shu");
        m.put("しょ", "sho");
        m.put("ちゃ", "cha");
        m.put("ちゅ", "chu");
        m.put("ちょ", "cho");
        m.put("にゃ", "nya");
        m.put("にゅ", "nyu");
        m.put("にょ", "nyo");
        m.put("ひゃ", "hya");
        m.put("ひゅ", "hyu");
        m.put("ひょ", "hyo");
        m.put("りゃ", "rya");
        m.put("りゅ", "ryu");
        m.put("りょ", "ryo");
        m.put("ぎゃ", "gya");
        m.put("ぎゅ", "gyu");
        m.put("ぎょ", "gyo");
        m.put("じゃ", "ja");
        m.put("じゅ", "ju");
        m.put("じょ", "jo");
        m.put("てぃ", "ti");
        m.put("でぃ", "di");
        m.put("つぃ", "tsi");
        m.put("ぢゃ", "dya");
        m.put("ぢゅ", "dyu");
        m.put("ぢょ", "dyo");
        m.put("びゃ", "bya");
        m.put("びゅ", "byu");
        m.put("びょ", "byo");
        m.put("ぴゃ", "pya");
        m.put("ぴゅ", "pyu");
        m.put("ぴょ", "pyo");
        m.put("ー", "-");
        m.put("ア", "a");
        m.put("イ", "i");
        m.put("ウ", "u");
        m.put("エ", "e");
        m.put("オ", "o");
        m.put("カ", "ka");
        m.put("キ", "ki");
        m.put("ク", "ku");
        m.put("ケ", "ke");
        m.put("コ", "ko");
        m.put("サ", "sa");
        m.put("シ", "shi");
        m.put("ス", "su");
        m.put("セ", "se");
        m.put("ソ", "so");
        m.put("タ", "ta");
        m.put("チ", "chi");
        m.put("ツ", "tsu");
        m.put("テ", "te");
        m.put("ト", "to");
        m.put("ナ", "na");
        m.put("ニ", "ni");
        m.put("ヌ", "nu");
        m.put("ネ", "ne");
        m.put("ノ", "no");
        m.put("ハ", "ha");
        m.put("ヒ", "hi");
        m.put("フ", "fu");
        m.put("ヘ", "he");
        m.put("ホ", "ho");
        m.put("マ", "ma");
        m.put("ミ", "mi");
        m.put("ム", "mu");
        m.put("メ", "me");
        m.put("モ", "mo");
        m.put("ヤ", "ya");
        m.put("ユ", "yu");
        m.put("ヨ", "yo");
        m.put("ラ", "ra");
        m.put("リ", "ri");
        m.put("ル", "ru");
        m.put("レ", "re");
        m.put("ロ", "ro");
        m.put("ワ", "wa");
        m.put("ヲ", "wo");
        m.put("ン", "n");
        m.put("ガ", "ga");
        m.put("ギ", "gi");
        m.put("グ", "gu");
        m.put("ゲ", "ge");
        m.put("ゴ", "go");
        m.put("ザ", "za");
        m.put("ジ", "ji");
        m.put("ズ", "zu");
        m.put("ゼ", "ze");
        m.put("ゾ", "zo");
        m.put("ダ", "da");
        m.put("ヂ", "ji");
        m.put("ヅ", "zu");
        m.put("デ", "de");
        m.put("ド", "do");
        m.put("バ", "ba");
        m.put("ビ", "bi");
        m.put("ブ", "bu");
        m.put("ベ", "be");
        m.put("ボ", "bo");
        m.put("パ", "pa");
        m.put("ピ", "pi");
        m.put("プ", "pu");
        m.put("ペ", "pe");
        m.put("ポ", "po");
        m.put("キャ", "kya");
        m.put("キュ", "kyu");
        m.put("キョ", "kyo");
        m.put("シャ", "sha");
        m.put("シュ", "shu");
        m.put("ショ", "sho");
        m.put("チャ", "cha");
        m.put("チュ", "chu");
        m.put("チョ", "cho");
        m.put("ニャ", "nya");
        m.put("ニュ", "nyu");
        m.put("ニョ", "nyo");
        m.put("ヒャ", "hya");
        m.put("ヒュ", "hyu");
        m.put("ヒョ", "hyo");
        m.put("リャ", "rya");
        m.put("リュ", "ryu");
        m.put("リョ", "ryo");
        m.put("ギャ", "gya");
        m.put("ギュ", "gyu");
        m.put("ギョ", "gyo");
        m.put("ジャ", "ja");
        m.put("ジュ", "ju");
        m.put("ジョ", "jo");
        m.put("ティ", "ti");
        m.put("ディ", "di");
        m.put("ツィ", "tsi");
        m.put("ヂャ", "dya");
        m.put("ヂュ", "dyu");
        m.put("ヂョ", "dyo");
        m.put("ビャ", "bya");
        m.put("ビュ", "byu");
        m.put("ビョ", "byo");
        m.put("ピャ", "pya");
        m.put("ピュ", "pyu");
        m.put("ピョ", "pyo");
    }
    public String convert(String s) {
        StringBuilder t = new StringBuilder();
        for ( int i = 0; i < s.length(); i++ ) {
            if ( i <= s.length() - 2 )  {
                if ( m.containsKey(s.substring(i,i+2))) {
                    t.append(m.get(s.substring(i, i+2)));
                    i++;
                } else if (m.containsKey(s.substring(i, i+1))) {
                    t.append(m.get(s.substring(i, i+1)));
                } else if ( s.charAt(i) == 'っ' ||s.charAt(i) =='ッ') {
                    t.append(m.get(s.substring(i+1, i+2)).charAt(0));
                } else {
                    t.append(s.charAt(i));
                }
            } else {
                if (m.containsKey(s.substring(i, i+1))) {
                    t.append(m.get(s.substring(i, i+1)));
                } else {
                    t.append(s.charAt(i));
                }
            }
        }
        return t.toString();
    }}